### ISSUE TITLE
Add Custom Class To Navigation Buttons?

### ISSUE THREAD

**Issue by chobo2** [techlab/jquery-smartwizard#106]
Hi

Is it possible to add your own classes to the navigation buttons(next, previous)?

**Comment by argawow** [comment]
Hi,
I am also looking for such a solution. I have an cancel navigation button and whant them to be red.

**Comment by ap-coder** [comment]
I also would like this

**Comment by techlab** [comment]
Instead you can overwrite the CSS settings of the buttons on your css file

```css
.sw-btn-next {
    color: white !important;
    background-color: red !important;
}

.sw-btn-prev {
    color: white !important;
    background-color: red !important;
}
```
